import pygame
import abc

from typing import List

from .control_type import ControlType
from ..view.board_view import BoardView

class Controller(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def handle_events(self, board_view: BoardView) -> ControlType:
        """
        Handle the stream of events generated by the user, update the board accordingly
        """
        raise NotImplementedError